SantaClausHarmadikBeadando/Models/ErrorViewModel.cs
using System;

namespace SantaClausHarmadikBeadando.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SantaClausHarmadikBeadando/Models/SantaClaus.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;


namespace SantaClausHarmadikBeadando.Models
{
    public class SantaClaus
    {

        // Kulcs
        [Key]
        public int ID { get; set; }

        [Required]
        [Display(Name = "Név")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Szín")]
        public string Colour { get; set; }

        // Pozitív szám megkötés
        [Required]
        [Display(Name = "Súly")]
        [Range(1, int.MaxValue, ErrorMessage = "A kívánság súlyának pozitív számnak kell lenni!")]
        public int Weigth { get; set; }

        // 1-10 határ megkötés
        [Required]
        [Display(Name = "Prioritás")]
        [Range(1, 10)]
        public int Priority { get; set; }

    }
}

SantaClausHarmadikBeadando/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SantaClausHarmadikBeadando.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SantaClausHarmadikBeadando.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SantaClausHarmadikBeadando/Controllers/SantaClausController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SantaClausHarmadikBeadando.Context;
using SantaClausHarmadikBeadando.Models;

namespace SantaClausHarmadikBeadando.Controllers
{
    public class SantaClausController : Controller
    {
        private readonly EFContext _context;

        public SantaClausController(EFContext context)
        {
            _context = context;
        }

        // GET: SantaClaus
        public async Task<IActionResult> Index()
        {
            // Növekvő sorrendben a prioritás szerint.
            return View(await _context.Wishes.OrderByDescending(p => p.Priority).ToListAsync());
        }

        // GET: SantaClaus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var santaClaus = await _context.Wishes
                .FirstOrDefaultAsync(m => m.ID == id);
            if (santaClaus == null)
            {
                return NotFound();
            }

            return View(santaClaus);
        }

        // GET: SantaClaus/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SantaClaus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Colour,Weigth,Priority")] SantaClaus santaClaus)
        {
            if (ModelState.IsValid)
            {
                var checkName = checkIfNameIsAlreadyPresent(santaClaus.Name);

                if (checkName)
                {
                    ModelState.AddModelError("Name", "Ne kívánd ezt többször te kis mohó, mert egyszer sem kapod meg !");
                } 
                else
                {
                    _context.Add(santaClaus);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));     // nameof(index)
                }

                
            }
            return View(santaClaus);
        }

        // Nézzük meg, hogy van-e már ilyen név
        public bool checkIfNameIsAlreadyPresent(string name)
        {
            using (var context = new EFContext())
            {
                var wishes = context.Wishes.ToList();

                foreach (var wish in wishes)
                {
                    if (wish.Name == name)
                    {
                        return true;
                    }
                }
            }


            return false;
        }

        // GET: SantaClaus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var santaClaus = await _context.Wishes.FindAsync(id);
            if (santaClaus == null)
            {
                return NotFound();
            }
            return View(santaClaus);
        }

        // POST: SantaClaus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Colour,Weigth,Priority")] SantaClaus santaClaus)
        {
            if (id != santaClaus.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(santaClaus);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SantaClausExists(santaClaus.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(santaClaus);
        }

        // GET: SantaClaus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var santaClaus = await _context.Wishes
                .FirstOrDefaultAsync(m => m.ID == id);
            if (santaClaus == null)
            {
                return NotFound();
            }

            return View(santaClaus);
        }

        // POST: SantaClaus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var santaClaus = await _context.Wishes.FindAsync(id);
            _context.Wishes.Remove(santaClaus);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SantaClausExists(int id)
        {
            return _context.Wishes.Any(e => e.ID == id);
        }
    }
}

SantaClausHarmadikBeadando/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SantaClausHarmadikBeadando/Views/SantaClaus/Create.cshtml
@model SantaClausHarmadikBeadando.Models.SantaClaus

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SantaClaus</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Colour" class="control-label"></label>
                <input asp-for="Colour" class="form-control" />
                <span asp-validation-for="Colour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weigth" class="control-label"></label>
                <input asp-for="Weigth" class="form-control" />
                <span asp-validation-for="Weigth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Priority" class="control-label"></label>
                <input asp-for="Priority" class="form-control" />
                <span asp-validation-for="Priority" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SantaClausHarmadikBeadando/Views/SantaClaus/Delete.cshtml
@model SantaClausHarmadikBeadando.Models.SantaClaus

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SantaClaus</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Colour)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Colour)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Weigth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Weigth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Priority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Priority)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SantaClausHarmadikBeadando/Views/SantaClaus/Details.cshtml
@model SantaClausHarmadikBeadando.Models.SantaClaus

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SantaClaus</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Colour)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Colour)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Weigth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Weigth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Priority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Priority)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SantaClausHarmadikBeadando/Views/SantaClaus/Edit.cshtml
@model SantaClausHarmadikBeadando.Models.SantaClaus

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SantaClaus</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" readonly />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Colour" class="control-label"></label>
                <input asp-for="Colour" class="form-control" />
                <span asp-validation-for="Colour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weigth" class="control-label"></label>
                <input asp-for="Weigth" class="form-control" readonly />
                <span asp-validation-for="Weigth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Priority" class="control-label"></label>
                <input asp-for="Priority" class="form-control" />
                <span asp-validation-for="Priority" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SantaClausHarmadikBeadando/Views/SantaClaus/Index.cshtml
@model IEnumerable<SantaClausHarmadikBeadando.Models.SantaClaus>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Colour)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weigth)
            </th>
         <!--   A prioritást nem kéri a feladat megjeleníteni
        <th>  
            @Html.DisplayNameFor(model => model.Priority)
        </th>
         //-->
            <th></th>
        </tr>
        </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Colour)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Weigth)
            </td>
            <!-- A prioritást nem kéri a feladat megjeleníteni
            <td>
                @Html.DisplayFor(modelItem => item.Priority)
            </td>
            //-->
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
            }
                </tbody>
            </table>

SantaClausHarmadikBeadando/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SantaClausHarmadikBeadando</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SantaClausHarmadikBeadando</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SantaClaus" asp-action="Index">SantaClaus</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SantaClausHarmadikBeadando - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>